### ISSUE TITLE
I should be able to fill text area to point out my personal views about the course in details.

### ISSUE THREAD

**Issue by kamenco** [kamenco/lovr2run#3]
**Acceptance criterea**
+ To make the text area using HTML and CSS for styling and validation.

**Task**
- [ ] Create the textarea
- [ ] The text area should hold no more than 120 characters
- [ ] Test the functionality.
